### ISSUE TITLE
incompatible with uvloop because of access to private attribute _protocol

### ISSUE THREAD

**Issue by nihlaeth** [cole/aiosmtplib#18]
I'm using [uvloop](https://github.com/MagicStack/uvloop) because of the significant speed up that it provides. However this seems to be incompatible with using the starttls method.

minimal example (put in actual connection information before running):
```python
import asyncio
import uvloop
asyncio.set_event_loop_policy(uvloop.EventLoopPolicy())

import aiosmtplib

async def connect(loop):
    smtp = aiosmtplib.SMTP(
        loop=loop,
        hostname=localhost,
        port=port,
        use_tls=True)
    await smtp.connect(use_tls=False, port=port)
    await smtp.starttls(validate_certs=False)

if __name__ == "__main__":
    loop = asyncio.get_event_loop()
    loop.run_until_complete(connect(loop))
```

result
```
Traceback (most recent call last):
  File "minimal_example.py", line 19, in <module>
    loop.run_until_complete(connect(loop))
  File "uvloop/loop.pyx", line 1203, in uvloop.loop.Loop.run_until_complete (uvloop/loop.c:25632)
  File "minimal_example.py", line 15, in connect
    await smtp.starttls(validate_certs=False)
  File "/git/dnd/lib64/python3.6/site-packages/aiosmtplib/esmtp.py", line 193, in starttls
    tls_context, server_hostname=server_hostname, timeout=timeout)
  File "/git/dnd/lib64/python3.6/site-packages/aiosmtplib/protocol.py", line 209, in starttls
    tls_context, server_hostname=server_hostname, waiter=waiter)
  File "/git/dnd/lib64/python3.6/site-packages/aiosmtplib/protocol.py", line 82, in upgrade_transport
    self.reader._transport._protocol = tls_protocol  # type: ignore
AttributeError: 'uvloop.loop.TCPTransport' object has no attribute '_protocol'
```

**Comment by cole** [comment]
Hmmm, uvloop seems to handle protocols and transports a bit differently internally.

Unfortunately there is no public API to upgrade an asyncio connection in place yet, so it's understandable that uvloop behaves differently. I'll see if I can find a way to get it working.

**Comment by cole** [comment]
It's working for me now. Can you try again with current master?

**Comment by nihlaeth** [comment]
It works on my end, awesome!

Could you make a new release for pypi so that I can update the minimum version requirement in my project setup.py?

**Comment by cole** [comment]
1.0.1 released.

**Comment by nihlaeth** [comment]
Thanks!
